name: 自动抓取
on:
 workflow_dispatch:
 schedule:
    - cron: '*/120 * * * *'
env:
  TZ: Asia/Shanghai # 时区
jobs:
  Spider:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v3
    - name: 启动 clash 
      run: |
        cd src/speedtest/clash 
        chmod +x ./clash
        nohup ./clash -d . &
        cd /home/runner/work/wally/wally
    - name: 安装node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - name: 安装依赖
      run: npm i
    - name: 下载订阅并合并
      run: node src
    - name: 测速
      run: node src/speedtest
    - name: 提交更改
      run: |                 
         git config --local user.email "action@workflows.com"
         git config --local user.name "action@workflows"
         git add ./
         git commit -m "啥也不是"
    - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
         github_token: ${{ github.token }}
         branch: main
     
    - name: SpeedtestCDN   
      run: curl https://purge.jsdelivr.net/gh/git-wally94/wally@main/speedtest.yaml
    - name: NodesCDN   
      run: curl https://purge.jsdelivr.net/gh/git-wally94/wally@main/nodes.yaml
    - name: sh_speedtest   
      run: curl ${{ github.sh_speedtest }}




